### ISSUE TITLE
[✨FEAT✨]: Create a basic urdf description for the moa

### ISSUE THREAD

**Issue by Jack17432** [UOA-FSAE/autonomous#21]
### Is there an existing enhancement request for this?

- [X] I have searched the existing feature requests

### Description

This basicly just needs to be a box of the dimentions of the moa so that we can know if the car is going to hit somthing or not. If you want you can make it as in depth as you want or make a mesh for it so that we can nicely visualise the car.

**Comment by Tanish29** [comment]
Plan:
1)	Install ros2 on windows as docker containers don’t allow for using device display
2)	Figure out the components of the car to model and which one will be the link and joint (I will be using meshes) – initially will start of simple but as I progress may add on more components of the car and sensors/cameras once confirmed
3)	Export the planned meshes as stl files.
4)	Measure and record the origin of each link
5)	Create 4 xacro files and 1 urdf.xacro file. The 4 files will be constants, links, joints, and macros. The 1 file will be a urdf file which includes all the other files – this structure could change.
6)	Code it up
7)	Create a robot state publisher
8)	Run the file in ros2 (rvis should pop up) and test
Initial car components will be:
-	Main body (chassis), suspension arms, wheels, steering wheel, sensors, lidars and cameras

**Comment by Tanish29** [comment]
![image](https://user-images.githubusercontent.com/45930444/236591951-51dbcc81-dbe4-4bcb-81c2-195d50c59ab7.png)
