### ISSUE TITLE
[✨FEAT✨]: Build and run scripts

### ISSUE THREAD

**Issue by Jack17432** [UOA-FSAE/autonomous#22]
### Is there an existing enhancement request for this?

- [X] I have searched the existing feature requests

### Description

A script to build the docker container or run the docker container.

### Additional Information

Could use a Makefile to make it more simple to detect what system the commands are being run on.

**Comment by csprono** [comment]
## OS/Architecture Detection
### Windows
- Detect by reading environment variables
  - OS = should return Windows_NT
  -  PROCESSOR_ARCHITECTURE = return x86 or AMD64
  -  PROCESSOR_ARCHITEW6432 = return AMD64 or undefined

### Linux
- Detect using uname command
  - uname -s = should return Linux
  - uname -p = output should contain either arm, x86_64 or something else

### OS X 
- Detect using uname command
  - uname -s = should return Darwin
  - uname -p = output should contain either arm, x86_64 or something else

### Example Code (modified from [here](https://gist.github.com/trosendal/d4646812a43920bfe94e))
```makefile
## Eight different machines are defined below,(2 windows                    
## and 6 Unix). Use the machine variable to build your process              
## differently by machine type.                                             

ifeq ($(OS),Windows_NT)
	MACHINE = WIN32
	ifeq ($(PROCESSOR_ARCHITEW6432),AMD64)
        CCFLAGS += -D AMD64
    else
		ifeq ($(PROCESSOR_ARCHITECTURE),AMD64)
			MACHINE += AMD64
		endif
		ifeq ($(PROCESSOR_ARCHITECTURE),x86)
			MACHINE += IA32
		endif
	endif
else
	UNAME_S := $(shell uname -s)
	ifeq ($(UNAME_S),Linux)
		MACHINE = LINUX
	endif
	ifeq ($(UNAME_S),Darwin)
		MACHINE = OSX
	endif
	UNAME_P := $(shell uname -p)
	ifeq ($(UNAME_P),x86_64)
		MACHINE += AMD64
	endif
	ifneq ($(filter %86,$(UNAME_P)),)
		MACHINE += IA32
	endif
	ifneq ($(filter arm%,$(UNAME_P)),)
		MACHINE += ARM
	endif
endif

all:
	echo $(MACHINE)
	echo $(PROCESSOR_ARCHITEW6432)
```

**Comment by csprono** [comment]
## Prerequisite Detection
[__Could Help__](https://stackoverflow.com/questions/5618615/check-if-a-program-exists-from-a-makefile)

### Windows 
- where command
  - e.g.
  	```makefile
  	ifeq ($(shell where nvcc),)
    ```	

### Linux/OS X
- which command 
  - e.g.
  	```makefile
  	ifeq ($(shell which nvcc),)
    ```	

## NVIDIA GPU Detection/Passthrough
### Detection
#### Windows
- wmic commmand 
  - e.g.
  	```
  	wmic path win32_VideoController get name
    ```
- check output for NVIDIA

#### Linux/OS X
- lspci command with grep 
  - e.g.
  	```
    lspci | grep -i 'vga\|3d\|2d'
	```

### Passthrough
- if NVIDIA GPU present run GPU enabled dockerfile
- else run CPU only dockerfile

**Comment by Jack17432** [comment]
looks good but can you give me an example how how to use it like:

Clone repo
cd into repo
use commad `make launch ` or somthing 
starts up dev container
enter it using vscode remote or somthing
...

**Comment by Jack17432** [comment]
As well as give me a list of the commands you enter and what there expected outputs are

**Comment by csprono** [comment]
## Usage Example
1. clone repo
2. cd into repo
3. use command ```make init``` for first time setup
4. check that docker is running
5. attach to running container (dev containers command)
