### ISSUE TITLE
[✨FEAT✨]: Msg and Srv interfaces 

### ISSUE THREAD

**Issue by Jack17432** [UOA-FSAE/autonomous#6]
### Is there an existing enhancement request for this?

- [X] I have searched the existing feature requests

### Description

Create a package that contains all of the custom ros2 Msg and Srv that the ws uses

### Additional Information

List of Msg interfaces

- [x]  CAN

List of Srv interfaces

- [x]  CAN

**Comment by Jack17432** [comment]
Plan

- [ ]  Create MOA_Commons pkg
- [ ]  Create Msg interfaces
- [ ]  Create Srv interfaces

---

 Msg interface for can needs to have the ID of the can message the RTR feld and 8 bytes of data the the can message holds. The RTR should defult false since a morjorty of the time it will not be set and so saves on readablilty. As well as each feild in the data should defult to zero as to save on bugs and readability of the code.

example:

uint32 id
bool is_rtr = false
uint8[8] data = [0, 0, 0, 0, 0, 0, 0, 0]

---

The CAN srv should be the exact same as the can message but should return a bool of if it is sent or not. 

example:

uint32 id
bool is_rtr = false
uint8[8] data = [0, 0, 0, 0, 0, 0, 0, 0]
\---
bool sent

---
please comment below if you think I have missed a custom common message type that we will be using.

**Comment by csprono** [comment]
This looks about right. I can't think of any other custom msg/srv we may need because I'm pretty sure you can download the ackermann msgs from apt.
