### ISSUE TITLE
[✨FEAT✨]: Ackerman to MoTec node

### ISSUE THREAD

**Issue by Jack17432** [UOA-FSAE/autonomous#7]
### Is there an existing enhancement request for this?

- [X] I have searched the existing feature requests

### Description

Take ackermann as input and and outputs a CAN service message.

### Additional Information

topic/cmd_val that has stamped ackermann msg 

then process info and send msg to CAN interface node with CAN service

This is safety critical (need way of knowing if unable to send msg/crash etc.)

**Comment by csprono** [comment]
**Input**
- Stamped Ackermann message
        - From topic/cmd_val

**Error handling/safety**
- If can't send message
       - print warning msg 
       - try resend msg
- if sys crash
       - emergency stop car (send braking signal)
       - deactivate node
       - print error msg
 NB: maybe detect crash with separate node sending a heartbeat so often (if dont receive throw sys crash error)

**Tests**
- simulate unsuccessful msg
- simulate sys crash
- simulate successful msg

**Parameters**
- use yaml file for launch params
- parameters
      - CAN bus connection id
[Ackerman to MoTec Node.docx](https://github.com/UOA-FSAE/autonomous/files/10810713/Ackerman.to.MoTec.Node.docx)

**Comment by Jack17432** [comment]
I would also say that this node should publish to the diagnostics topic. This is what I have read as the common way of making sure safety crit systems are alive.

**Comment by Jack17432** [comment]
Also I am thinking that the motec should be the one triggering the Ebrake and so you don't have to worry about this node triggering the break system and all it needs to do it turn the ackerman steering msgs into can messages

**Comment by csprono** [comment]
**Input**
- Stamped Ackermann message
     - From topic/cmd_val

**Error handling/safety**
- If can't send message
    - print warning msg
    - try resend msg

- if sys crash
     - emergency stop car (send braking signal)
     - deactivate node
     - print error msg
NB: maybe detect crash with separate node sending a heartbeat so often (if dont receive throw sys crash error)

**Tests**
- simulate unsuccessful msg
- simulate sys crash
- simulate successful msg

Parameters
- use yaml file for launch params if there are any
[Ackerman to MoTec Node.docx](https://github.com/UOA-FSAE/autonomous/files/10835878/Ackerman.to.MoTec.Node.docx)

**Comment by csprono** [comment]
- [ ] create package
- [ ] create minimal/basic nodes
- [ ] create server
- [ ] create subscriber
- [ ] create translation between Ackermann and CAN
- [ ] implement crash detection (heartbeat)
- [ ] implement error handling
- [ ] create tests

**Comment by Jack17432** [comment]
Also the steering angle can be negative so how are you gonna translate into an unsigned int. Once you anserw that then you can start coding :)

**Comment by csprono** [comment]
For negative ackermann values use twos complement. Flip all bits and add 1 to LSB.
